export const SHOW_PACKAGE_INFO = 'SHOW_PACKAGE_INFO';
export const MOUNT_PACKAGES = 'MOUNT_PACKAGES';
export const MOUNT_NODES = 'MOUNT_NODES';
export const MOUNT_LOADED_COUNTER = 'MOUNT_LOADED_COUNTER';
